import styled from "styled-components";
import { Link } from "react-router-dom";

export const NavigationContainer = styled.div`
  background-color: white;
  height: auto;
  width: 100%;
  display: flex;
  justify-content: space-between;
  margin-bottom: 25px;
  position: sticky;
  top: 0;
  z-index: 1;
`;

export const LogoContainer = styled(Link)`
  display: flex;
  height: 100%;
  width: auto;
  padding: 1rem;
  align-items: center;

  @media (max-width: 420px) {
    display: flex;
    justify-content: center;
    align-items: center;
  }
`;

export const NavRigthModule = styled.div`
  display: flex;
  flex-direction: column;
`;

export const UserName = styled.span`
  position: absolute;
  font-size: 0.8rem;
  font-weight: 600;
  text-align: right;
  padding: 0.2rem 0.5rem;
  border-radius: 5px 5px 0 0;
  top: -5px;
  right: 0.8rem;
  background-color: #4d004d;
  color: white;
  box-shadow: rgba(27, 31, 35, 0.04) 0px 1px 0px,
    rgba(255, 255, 255, 0.25) 0px 1px 0px inset;
  animation: swing-in-bottom-fwd 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275)
    both;

  /* ----------------------------------------------
 * Generated by Animista on 2022-9-22 21:3:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation swing-in-bottom-fwd
 * ----------------------------------------
 */
  @keyframes swing-in-bottom-fwd {
    0% {
      -webkit-transform: rotateX(100deg);
      transform: rotateX(100deg);
      -webkit-transform-origin: bottom;
      transform-origin: bottom;
      opacity: 0;
    }
    100% {
      -webkit-transform: rotateX(0);
      transform: rotateX(0);
      -webkit-transform-origin: bottom;
      transform-origin: bottom;
      opacity: 1;
    }
  }
`;

export const NavLinks = styled.div`
  width: auto;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: flex-end;
`;

export const NavLink = styled(Link)`
  text-align: center;
  padding: 10px 15px;
  cursor: pointer;
`;
